Support for Factura C
ombulabs/afip_bill pull request #6
Opened 2018-05-09 12:54 UTC by etagwerker

Hola @lubc, 

Acá está el PR de los cambios que hizo @emafriedrich

Por favor revisá que esté todo OK.

2018-05-11 19:39 UTC, lubc requested changes
Dejé algunos comentarios. Además también habría que actualizar la documentación (simplemente mencionar `11 => C`) y los tests

2018-05-11 19:39 UTC, lubc commented on lib/afip_bill/generator.rb
> +    attr_reader :afip_bill, :bill_type, :user, :line_items, :duplicado_original
Deberíamos eliminar todo lo relacionado a `duplicado_original` en este PR, parecería ser simplemente una solución temporal para #4

2018-05-11 19:39 UTC, lubc commented on lib/afip_bill/generator.rb
> +    BRAVO_CBTE_TIPO = { "01" => "Factura A", "06" => "Factura B" , "11" => "Factura C"}.freeze
Esta constante no debería comenzar con `BRAVO_` (soy culpable). Estos códigos son algo de AFIP, por lo que `CBTE_TIPO` sería suficiente.

2018-05-11 19:39 UTC, lubc commented on lib/afip_bill/generator.rb
>      def type_a_or_b_bill
Este método ahora debería llamarse diferente, algo como `bill_type`

2018-05-11 19:39 UTC, lubc commented on lib/afip_bill/views/bills/factura_c.html.erb
> +
Este archivo es idéntico al de factura_b, estaría bueno reutilizar ese para evitar repetir código.

2018-05-17 20:15 UTC, etagwerker commented on lib/afip_bill/generator.rb
> +    attr_reader :afip_bill, :bill_type, :user, :line_items, :duplicado_original
@lubc Me parece bien eso. Me gusta la solución que tenemos en https://github.com/ombulabs/afip_bill/pull/8https://github.com/ombulabs/afip_bill/pull/8 porque es bastante flexible: Te permitiría tener un triplicado si querés. 

@emafriedrich tenés tiempo para trabajar en este pr? Lo abrí en base a tu branch para no duplicar horas de trabajo. 😸

2018-05-17 20:16 UTC, etagwerker commented on lib/afip_bill/generator.rb
> +    BRAVO_CBTE_TIPO = { "01" => "Factura A", "06" => "Factura B" , "11" => "Factura C"}.freeze
@lubc Me parece que esto es otro issue. Podés crear un issue nuevo para esto? No me parece una buena idea meter ese refactoreo acá.

2018-05-17 20:17 UTC, etagwerker commented on lib/afip_bill/generator.rb
>      def type_a_or_b_bill
@lubc de acuerdo con eso, pero después de mergear https://github.com/ombulabs/afip_bill/pull/8 no sé si este cambio es necesario.

2018-05-18 03:12 UTC, emafriedrich commented on lib/afip_bill/generator.rb
> +    attr_reader :afip_bill, :bill_type, :user, :line_items, :duplicado_original
@etagwerker por ahora estoy complicado. Pero si la sem que viene puedo. Revierto el codigo para mostrar "Duplicado" para en defenitiva quedarnos con #8 ?

2019-07-23 15:50 UTC, tcordeu commented
¿Hay chances de que este PR se mergee?

Si hacen falta cambios, estoy dispuesto a hacerlos.

2019-07-23 16:25 UTC, lubc commented
@tcordeu Sí, claro. Quedó pendiente hacer los cambios sugeridos en el code review. Y también resolver los git conflicts.

2019-07-23 17:01 UTC, tcordeu commented
@lubc Perfecto, mañana hago los cambios!

2019-07-24 12:42 UTC, tcordeu commented
@lubc Ahora que pienso, no tengo permisos de escritura en el fork de donde sale este PR ¿Que decis de hacer?

2019-11-04 13:09 UTC, etagwerker commented
@tcordeu Podrías abrir un nuevo fork con este branch y mandar un nuevo PR. 😉

2019-12-10 13:54 UTC, etagwerker commented
@lubc Cierro esto porque parece que esto ya se resolvió en este PR: https://github.com/ombulabs/afip_bill/pull/18

2019-12-10 13:54 UTC, closed without merging